-- ===============================================================
-- EHD wire-to-collector electrostatics (FEMM Lua script)
-- Generated by ehdpsu.femm -- OPEN AND RUN THIS IN FEMM LOCALLY.
--
-- FEMM is a Windows GUI/Lua tool and is NOT executed in the build
-- sandbox. To use this file: launch FEMM, then File > Open Lua Script
-- (or from the FEMM Lua console: dofile('ehd_wire_collector.lua')).
--
-- Design: r_wire = 0.025 mm, d_gap = 12.0 mm, depth (L_wire) = 150.0 mm, V_op = 22000.0 V.
-- Analytical cross-check (from ehdpsu.physics):
--   Peek onset surface field E_peek = 17756800.0 V/m
--   corona onset voltage    V_onset = 2740.6671272441477 V
-- FEMM solves the electrostatic (Laplace) field with NO space charge, so the peak wire-surface field it reports is the CORONA-ONSET field to compare against Peek's law, not the loaded operating field (ion space charge lowers the near-wire field once current flows).
-- ===============================================================

-- Parameters (millimetres; FEMM length unit set below).
r_wire = 0.025      -- emitter wire radius [mm]
d_gap = 12.0        -- emitter-to-collector gap [mm]
depth = 150.0        -- out-of-plane depth = wire length [mm]
outer_r = 120.0    -- outer air-boundary radius [mm]
collector_y = -12.025   -- collector plate y-position [mm]
collector_hw = 120.0 -- collector plate half-width [mm]
V_op = 22000.0             -- emitter operating voltage [V]

-- 1) New electrostatics document (mode 1).
newdocument(1)

-- 2) Problem definition: millimetres, planar, out-of-plane depth,
--    solver precision, min angle. Depth carries the wire length so
--    energy/charge results scale to the real cell.
ei_probdef("millimeters", "planar", 1e-8, depth, 30)

-- 3) Air material (relative permittivity 1).
ei_addmaterial("Air", 1, 1, 0)

-- 4) Boundary property: fixed-potential (Dirichlet) outer boundary at
--    0 V, an open-boundary approximation (outer_r >> gap).
-- ei_addboundprop(name, Vc, qs, c0, c1, BdryFormat) : BdryFormat 0 = fixed V.
ei_addboundprop("FarField", 0, 0, 0, 0, 0)

-- 5) Conductor properties: fix the wire at V_op and the collector at 0 V.
-- ei_addconductorprop(name, Vc, qc, ConductorType) : ConductorType 1 = fixed V.
ei_addconductorprop("Emitter", V_op, 0, 1)
ei_addconductorprop("Collector", 0, 0, 1)

-- 6) Geometry -----------------------------------------------------
-- Emitter wire: a circle of radius r_wire centred at the origin,
-- drawn as two 180-degree arcs between the left/right nodes.
ei_addnode(-r_wire, 0)
ei_addnode(r_wire, 0)
-- ei_addarc(x1, y1, x2, y2, angle_deg, maxseg)
ei_addarc(-r_wire, 0, r_wire, 0, 180, 1)
ei_addarc(r_wire, 0, -r_wire, 0, 180, 1)

-- Collector plate: a horizontal segment a distance d_gap below the
-- wire surface, spanning +/- collector_hw.
ei_addnode(-collector_hw, collector_y)
ei_addnode(collector_hw, collector_y)
ei_addsegment(-collector_hw, collector_y, collector_hw, collector_y)

-- Outer air boundary: a large box (open-boundary approximation).
ei_addnode(-outer_r, outer_r)
ei_addnode(outer_r, outer_r)
ei_addnode(outer_r, -outer_r)
ei_addnode(-outer_r, -outer_r)
ei_addsegment(-outer_r, outer_r, outer_r, outer_r)
ei_addsegment(outer_r, outer_r, outer_r, -outer_r)
ei_addsegment(outer_r, -outer_r, -outer_r, -outer_r)
ei_addsegment(-outer_r, -outer_r, -outer_r, outer_r)

-- 7) Assign boundary property to the four outer edges (midpoints).
ei_selectsegment(0, outer_r)
ei_selectsegment(outer_r, 0)
ei_selectsegment(0, -outer_r)
ei_selectsegment(-outer_r, 0)
ei_setsegmentprop("FarField", 0, 1, 0, 0, "<None>")
ei_clearselected()

-- 8) Assign the Emitter conductor to the wire arcs.
ei_selectarcsegment(0, r_wire)
ei_selectarcsegment(0, -r_wire)
ei_setarcsegmentprop(1, "<None>", 0, 0, "Emitter")
ei_clearselected()

-- 9) Assign the Collector conductor to the collector plate segment.
ei_selectsegment(0, collector_y)
ei_setsegmentprop("<None>", 0, 1, 0, 0, "Collector")
ei_clearselected()

-- 10) Block labels. THE GEOMETRY HAS THREE REGIONS, NOT ONE.
--
-- Corrected 2026-09-16, the first time this script was ever run in FEMM. It
-- previously placed ONE label, at (0, outer_r/2), and FEMM refused to solve with
-- "Material properties have not been defined for all regions". Every region a
-- closed boundary encloses needs a label, and this geometry closes three:
--
--   (a) the main air region, above the collector and outside the wire;
--   (b) the wire INTERIOR -- the two 180-degree arcs form a closed circle, so its
--       inside is its own region;
--   (c) the region BELOW the collector -- collector_hw equals outer_r, so the plate
--       spans the full width and its end nodes land on the side walls, partitioning
--       the box in two.
--
-- (b) and (c) are both physically inert and are labelled Air rather than excluded:
--   * inside a conductor held at a single potential the solution is constant, so
--     E = 0 there, contributing nothing to stored energy and nothing to the
--     conductor charge integral;
--   * below a grounded plate bounded by grounded walls every boundary sits at 0 V,
--     so that region solves to V = 0 throughout and E = 0.
--
-- FEMM 4.2 does offer a <No Mesh> block property, which would be tidier for (b) and
-- would save meshing a 25 um circle. It is NOT used here because its exact spelling
-- was not verified against this installation, and a wrong material name fails the
-- same way the missing label did. Air is already defined and cannot be misspelt.
ei_addblocklabel(0, outer_r * 0.5)
ei_selectlabel(0, outer_r * 0.5)
ei_setblockprop("Air", 1, 0, 0)
ei_clearselected()

-- (b) wire interior.
ei_addblocklabel(0, 0)
ei_selectlabel(0, 0)
ei_setblockprop("Air", 1, 0, 0)
ei_clearselected()

-- (c) below the collector plate.
ei_addblocklabel(0, (collector_y - outer_r) * 0.5)
ei_selectlabel(0, (collector_y - outer_r) * 0.5)
ei_setblockprop("Air", 1, 0, 0)
ei_clearselected()

-- 11) Zoom, save, mesh, solve, and load the solution.
ei_zoomnatural()
ei_saveas("ehd_wire_collector.fee")
ei_analyze(0)
ei_loadsolution()

-- 12) Read the outputs, in the script rather than by hand -------
--
-- Added 2026-09-16. This block previously described where to click and which
-- function to call, and it named eo_getconductorproperty -- which does not exist.
-- The function is eo_getconductorproperties, PLURAL, confirmed from FEMM's own
-- Octave wrapper at C:\femm42\mfiles\eo_getconductorproperties.m.
--
-- Computing the values here rather than reading them off the GUI removes the step
-- where a transcription error would enter, and it makes the reading reproducible:
-- the same script run twice gives the same numbers.
--
-- eo_getpointvalues(x, y) returns EIGHT values in this order, established from the
-- same wrapper set (eo_getv takes column 1, eo_getd 2:3, eo_gete 4:5, eo_getperm
-- 6:7, eo_getenergydensity 8):
--     V, Dx, Dy, Ex, Ey, ex, ey, energy_density
-- ---------------------------------------------------------------

-- DIALECT: FEMM 4.2 embeds Lua 4, where the maths and string functions are GLOBALS
-- (sqrt, cos, sin, format) and the math/string tables of Lua 5 do not exist. FEMM's
-- own readme refers to "the Lua format command" for exactly that reason. The shim
-- below makes this script run under either dialect: under Lua 4 the globals already
-- exist and nothing happens, under Lua 5 they are bound to their table members.
-- Radians are converted with a literal rather than PI, so the script does not depend
-- on which name the constant has.
if not sqrt then sqrt = math.sqrt end
if not cos then cos = math.cos end
if not sin then sin = math.sin end
if not format then format = string.format end
deg2rad = 0.0174532925199433

-- Peak surface field. Sampled just OUTSIDE the wire, because a point exactly on the
-- boundary may not lie in any element. Three radii are reported rather than one so
-- the radial sensitivity of the reading is visible instead of hidden: near a thin
-- wire the field falls roughly as 1/r, so a 1% offset costs about 1%. Record the
-- 1.005 figure and keep the other two -- the spread IS the reading's uncertainty.
function probe_ring(frac)
  Emax = 0
  th_at = 0
  i = 0
  while i < 360 do
    th = i * deg2rad
    xs = frac * r_wire * cos(th)
    ys = frac * r_wire * sin(th)
    V, Dx, Dy, Ex, Ey, ex, ey, nrg = eo_getpointvalues(xs, ys)
    if Ex then
      E = sqrt(Ex * Ex + Ey * Ey)
      if E > Emax then
        Emax = E
        th_at = i
      end
    end
    i = i + 1
  end
  print(format("E_peak at r = %.4f * r_wire : %.6e V/m  (peak at %d deg)",
               frac, Emax, th_at))
  return Emax
end

E_at_1005 = probe_ring(1.005)
E_at_101 = probe_ring(1.01)
E_at_102 = probe_ring(1.02)

-- Cell capacitance, two independent routes. They should agree; a DISAGREEMENT IS A
-- FINDING and must be reported rather than averaged away.
--
-- Route (a), stored energy: C = 2W / V_op^2. All three air blocks are selected
-- because the energy integral covers only what is selected -- and (b) and (c) hold
-- no energy, so including them is a check that they really are inert rather than an
-- approximation.
eo_clearblock()
eo_selectblock(0, outer_r * 0.5)
eo_selectblock(0, 0)
eo_selectblock(0, (collector_y - outer_r) * 0.5)
W = eo_blockintegral(0)
eo_clearblock()
C_from_energy = 2 * W / (V_op * V_op)

-- Route (b), emitter charge: C = Q / V_op.
Vc, Q = eo_getconductorproperties("Emitter")
C_from_charge = Q / V_op

print(format("W_stored_J        : %.6e", W))
print(format("C_from_energy_F   : %.6e", C_from_energy))
print(format("Q_emitter_C       : %.6e", Q))
print(format("C_from_charge_F   : %.6e", C_from_charge))
if C_from_charge ~= 0 then
  print(format("route ratio (energy/charge) : %.4f",
               C_from_energy / C_from_charge))
end

-- FEMM reports per the problem depth set in ei_probdef, which is the wire length,
-- so C is the whole-cell capacitance rather than a per-metre figure.
--
-- HOW TO CROSS-CHECK AGAINST PEEK, AND HOW NOT TO.
--
-- Corrected 2026-09-16, immediately after the first successful run. This block used to
-- direct the reader to compare the solved surface field against the analytical Peek
-- figure as though they were the same quantity. They are not, and the wording is
-- PARAPHRASED here rather than quoted, because a test scans this file for the old
-- sentence and quoting it verbatim would reproduce the very thing being retracted.
--
-- It was a CATEGORY ERROR and it would have manufactured a false alarm: the script
-- applies V_op, whereas Peek's figure is the surface field AT ONSET. On the MK0
-- geometry the two differ by a factor of about 7.4, so an operator following the old
-- wording would have reported a catastrophic disagreement where there is none.
--
-- The valid comparison uses the fact that Laplace is LINEAR in the applied voltage,
-- so one solve at any voltage gives the whole geometry:
--
--   1. field per volt from this run:      E_per_V = E_surface / V_op
--   2. onset is where E_surface = E_peek: V_onset_implied = E_peek / E_per_V
--   3. compare V_onset_implied against the closed-form V_onset in the header.
--
-- Differences come from the geometry the closed form assumes, from meshing, and from
-- the finite outer boundary. A disagreement is a result to report, NOT something to
-- tune the mesh until it goes away.
--
-- The capacitance has an independent analytical comparison of its own: for a wire at
-- height h above a ground plane, C' = 2*pi*eps0 / acosh(h/r) per unit length. Note
-- acosh(h/r), NOT ln(d/r) -- the image-charge form, not the coaxial approximation.
-- FEMM solves the electrostatic (Laplace) field with NO space charge, so the peak wire-surface field it reports is the CORONA-ONSET field to compare against Peek's law, not the loaded operating field (ion space charge lowers the near-wire field once current flows).
-- ===============================================================
