-- ===============================================================
-- EHD wire-to-collector electrostatics (FEMM Lua script)
-- Generated by ehdpsu.femm -- OPEN AND RUN THIS IN FEMM LOCALLY.
--
-- FEMM is a Windows GUI/Lua tool and is NOT executed in the build
-- sandbox. To use this file: launch FEMM, then File > Open Lua Script
-- (or from the FEMM Lua console: dofile('ehd_wire_collector.lua')).
--
-- Design: r_wire = 0.025 mm, d_gap = 12.0 mm, depth (L_wire) = 150.0 mm, V_op = 22000.0 V.
-- Analytical cross-check (from ehdpsu.physics):
--   Peek onset surface field E_peek = 17756800.0 V/m
--   corona onset voltage    V_onset = 2740.6671272441477 V
-- FEMM solves the electrostatic (Laplace) field with NO space charge, so the peak wire-surface field it reports is the CORONA-ONSET field to compare against Peek's law, not the loaded operating field (ion space charge lowers the near-wire field once current flows).
-- ===============================================================

-- Parameters (millimetres; FEMM length unit set below).
r_wire = 0.025      -- emitter wire radius [mm]
d_gap = 12.0        -- emitter-to-collector gap [mm]
depth = 150.0        -- out-of-plane depth = wire length [mm]
outer_r = 120.0    -- outer air-boundary radius [mm]
collector_y = -12.025   -- collector plate y-position [mm]
collector_hw = 120.0 -- collector plate half-width [mm]
V_op = 22000.0             -- emitter operating voltage [V]

-- 1) New electrostatics document (mode 1).
newdocument(1)

-- 2) Problem definition: millimetres, planar, out-of-plane depth,
--    solver precision, min angle. Depth carries the wire length so
--    energy/charge results scale to the real cell.
ei_probdef("millimeters", "planar", 1e-8, depth, 30)

-- 3) Air material (relative permittivity 1).
ei_addmaterial("Air", 1, 1, 0)

-- 4) Boundary property: fixed-potential (Dirichlet) outer boundary at
--    0 V, an open-boundary approximation (outer_r >> gap).
-- ei_addboundprop(name, Vc, qs, c0, c1, BdryFormat) : BdryFormat 0 = fixed V.
ei_addboundprop("FarField", 0, 0, 0, 0, 0)

-- 5) Conductor properties: fix the wire at V_op and the collector at 0 V.
-- ei_addconductorprop(name, Vc, qc, ConductorType) : ConductorType 1 = fixed V.
ei_addconductorprop("Emitter", V_op, 0, 1)
ei_addconductorprop("Collector", 0, 0, 1)

-- 6) Geometry -----------------------------------------------------
-- Emitter wire: a circle of radius r_wire centred at the origin,
-- drawn as two 180-degree arcs between the left/right nodes.
ei_addnode(-r_wire, 0)
ei_addnode(r_wire, 0)
-- ei_addarc(x1, y1, x2, y2, angle_deg, maxseg)
ei_addarc(-r_wire, 0, r_wire, 0, 180, 1)
ei_addarc(r_wire, 0, -r_wire, 0, 180, 1)

-- Collector plate: a horizontal segment a distance d_gap below the
-- wire surface, spanning +/- collector_hw.
ei_addnode(-collector_hw, collector_y)
ei_addnode(collector_hw, collector_y)
ei_addsegment(-collector_hw, collector_y, collector_hw, collector_y)

-- Outer air boundary: a large box (open-boundary approximation).
ei_addnode(-outer_r, outer_r)
ei_addnode(outer_r, outer_r)
ei_addnode(outer_r, -outer_r)
ei_addnode(-outer_r, -outer_r)
ei_addsegment(-outer_r, outer_r, outer_r, outer_r)
ei_addsegment(outer_r, outer_r, outer_r, -outer_r)
ei_addsegment(outer_r, -outer_r, -outer_r, -outer_r)
ei_addsegment(-outer_r, -outer_r, -outer_r, outer_r)

-- 7) Assign boundary property to the four outer edges (midpoints).
ei_selectsegment(0, outer_r)
ei_selectsegment(outer_r, 0)
ei_selectsegment(0, -outer_r)
ei_selectsegment(-outer_r, 0)
ei_setsegmentprop("FarField", 0, 1, 0, 0, "<None>")
ei_clearselected()

-- 8) Assign the Emitter conductor to the wire arcs.
ei_selectarcsegment(0, r_wire)
ei_selectarcsegment(0, -r_wire)
ei_setarcsegmentprop(1, "<None>", 0, 0, "Emitter")
ei_clearselected()

-- 9) Assign the Collector conductor to the collector plate segment.
ei_selectsegment(0, collector_y)
ei_setsegmentprop("<None>", 0, 1, 0, 0, "Collector")
ei_clearselected()

-- 10) Air block label (place inside the air region, between wire and
--     the outer boundary; avoid the wire interior).
ei_addblocklabel(0, outer_r * 0.5)
ei_selectlabel(0, outer_r * 0.5)
ei_setblockprop("Air", 1, 0, 0)
ei_clearselected()

-- 11) Zoom, save, mesh, solve, and load the solution.
ei_zoomnatural()
ei_saveas("ehd_wire_collector.fee")
ei_analyze(0)
ei_loadsolution()

-- 12) How to read the outputs -----------------------------------
-- Maximum surface field on the wire (compare with Peek's E_peek):
--   eo_selectblock / line-integral, or hover the wire surface and read
--   |E| from the point-value display. A quick numeric probe:
--     eo_addcontour(-r_wire, 0)
--     eo_addcontour(r_wire, 0)
--     Emax = eo_lineintegral(...)   -- see FEMM docs for the field code
--   Practically: use the density plot |E| and note the peak at the wire.
--
-- Cell capacitance (two independent routes; they should agree):
--   (a) From stored energy W:  C = 2 * W / V_op^2
--       W = eo_blockintegral(0)   -- 0 = stored electrostatic energy
--       (select the air block first with eo_selectblock).
--   (b) From conductor charge Q on the emitter:  C = Q / V_op
--       Q = eo_getconductorproperty('Emitter', 'charge') (FEMM >= 4.2).
--   FEMM reports per the set depth, so C is the whole-cell capacitance.
--
-- Cross-check: FEMM's peak wire-surface |E| should be close to the
-- analytical E_peek printed in the header (differences come from
-- meshing and the finite outer boundary). FEMM solves the electrostatic (Laplace) field with NO space charge, so the peak wire-surface field it reports is the CORONA-ONSET field to compare against Peek's law, not the loaded operating field (ion space charge lowers the near-wire field once current flows).
-- ===============================================================
